<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10927" started-at="2021-12-27T16:48:16Z" finished-at="2021-12-27T16:48:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10927" started-at="2021-12-27T16:48:16Z" finished-at="2021-12-27T16:48:27Z">
      <class name="org.flip.Flipkart">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:org.flip.Flipkart@598067a5]" name="beforeClass" is-config="true" duration-ms="3637" started-at="2021-12-27T16:48:16Z" finished-at="2021-12-27T16:48:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:org.flip.Flipkart@598067a5]" name="beforeMethod" is-config="true" duration-ms="7" started-at="2021-12-27T16:48:20Z" finished-at="2021-12-27T16:48:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="test()[pri:0, instance:org.flip.Flipkart@598067a5]" name="test" duration-ms="6340" started-at="2021-12-27T16:48:20Z" finished-at="2021-12-27T16:48:26Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at org.flip.Flipkart.test(Flipkart.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:org.flip.Flipkart@598067a5]" name="afterMethod" is-config="true" duration-ms="0" started-at="2021-12-27T16:48:26Z" finished-at="2021-12-27T16:48:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:org.flip.Flipkart@598067a5]" name="afterClass" is-config="true" duration-ms="878" started-at="2021-12-27T16:48:26Z" finished-at="2021-12-27T16:48:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- org.flip.Flipkart -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
